### PR TITLE
Makes color picker dialog responsive and adds cpWidth parameter

### PR DESCRIPTION
**Pull request by sconix**
This makes the need for cpHeight obsolete by making the dialog responsive. Added cpWidth parameter can be used to set the width of the dialog (to match the directive width with top/bottom placement for example).

### CODE REVIEW

**Comment by Alberplz** [comment]
Hi
I see a line under the top slider and the text alpha control is outside
cp

**Comment by sconix** [comment]
Let me try to re-produce this, maybe browser default styles are messing it up and I am missing some reset styles. What browser did you test with?

**Comment by sconix** [comment]
I added the style fixes that should correct those issues you were seeing. I could not reproduce the extra white space after the preset colors though. So if that is a still issue then let me know the browser you tested with and I try to reproduce it. Also please let me know if you want me to do any changes.

**Comment by Alberplz** [comment]
Hi
Fails in Internet Explorer 11 and Safari(5.1.7)
Same problem, text inputs overfow color picker dialog when is selected rgba or hsla

**Comment by sconix** [comment]
I am pretty sure I tested with those and fixed that problem as well. Let me check once I get back to my computer that if I forget to commit them, it seems that I only see one commit in here so I guess I accidentally left that commit unpushed.

**Comment by Alberplz** [comment]
Internet Explorer is OK, In Safari(5.1.7) for windows and I see:
safari

What version are you using?

**Comment by Alberplz** [comment]
The new 2 options a very nice, but could be possible having the sliders, color selected...with the same widths and positions please? I would be nice the color picker to have the same appearence in all versions.
In the template folder could be added news templates...

**Comment by sconix** [comment]
I tested with latest safari in OS X. Isn't the windows Safari like really old? I am not sure if that should be supported, not sure if Angular 2 even supports such old version of Safari. At least as far as I know the preferred way to do layouts in Angular 2 is flexbox and those really old browsers wont support that.

Not sure what you mean with your latest comment. The appearance should be the same as previously.

**Comment by Alberplz** [comment]
If works with Safari (7+) is OK, (now I cant access to mac a to test in Safari), could you validate that?

My last comment, sliders width, paddings...:
colorpickers

**Comment by sconix** [comment]
Yes I tested with OS X and safari 7 and it looks the same as in Chrome, Firefox and IE 11.

Ok I get it now, I try to tweak the paddings / width closer to the originals. So give me an hour and I will update the pull request.

**Comment by sconix** [comment]
I changed the paddings closer to your original paddings and there should now be only really small difference which I left in for more consistent padding values around the widget. I hope they are now to your liking.

I also merged changes from your master branch for this and the preset colors pull request.

**Comment by Alberplz** [comment]
`<input [colorPicker]="color" (colorPickerChange)="hex8=onChangeColor($event)"/>`

**Pull request merged**
