### PR TITLE
Moved to using Typescript 2.0.0

### PR DESCRIPTION
**Pull request by sconix**
This gets rid of the need for separate typings tool and configuration.

### CODE REVIEW

**Comment by Alberplz** [comment]
Hi
Maybe we should respect versions from Angular2 quickstart https://angular.io/docs/ts/latest/quickstart.html, ¿what do you think?

**Comment by sconix** [comment]
Well angular-cli has already moved to typescript 2 couple releases a go so having two separate typings setups wont make sense. But yes this can hold of until the quickstart updates since I think its just matter of which to follow angular-cli setup or the quickstart.

**Comment by BrainCrumbz** [comment]
Actually, now that angular 2 final is out, they reference typescript 2.0.2 so it might be a good time to do the move

**Comment by BrainCrumbz** [comment]
Hi again. Same as before: could you please shed some light on what has been decided? Thanks

**Comment by sconix** [comment]
I can gladly update / verify the pull request to work with the latest version if Alberplz wants to move to using typescript 2.

**Pull request closed without merging**
