### PR TITLE
chore(repo): stop tracking build outputs

### PR DESCRIPTION
**Pull request by BrainCrumbz**

### CODE REVIEW

**Comment by BrainCrumbz** [comment]
@Alberplz if you're willing to consider this PR (and the other pending one as well, BTW) we can work at it again and resolve conflicts after recent changes.

**Comment by cmckni3** [comment]
I'm not sure bower would work after this change is merged. I prefer npm but some prefer bower.

Also, I would add a *prepublish* script to the package.json which calls `npm run build`

**Comment by BrainCrumbz** [comment]
@cmckni3 haven't used bower for some time now, so maybe someone with more up-to-date info can chime in. But as far as usual best practices, you don't store build output/artifacts under source control, just for the fact that whatever tool needs those, there should be some command to recreate them.

So I guess that if bower needs them at some point in build process, there should be a previous build step that recreate those.

BTW @Alberplz we can resolve current conflicts if you plan on merging this PR at some point

**Comment by cmckni3** [comment]
@BrainCrumbz I have up-to-date information. I have built many projects using bower.

I agree with not putting the artifacts in the repo. Unfortunately, you have to for it to be compatible with bower. I looked through many large open source projects and they keep the built version of the library in the repo to be compatible with bower.

Take a look at [moment](https://github.com/moment/moment), [knockout](https://github.com/knockout/knockout/tree/v3.4.0), etc.

It appears most projects are taking a new approach to releasing with bower. Bower depends on tags in git and the `main` key of `bower.json`. Some maintainers are adding their `dist`/`build` folder to the tagged commit.

This and the fact that I need another dependency in my project is why I don't use bower anymore.

**Comment by BrainCrumbz** [comment]
I see. Well, I guess this PR should be ignored and closed then.

**Pull request closed without merging**
