### PR TITLE
Feature#make npm package

### PR DESCRIPTION
**Pull request by Csini**
This is a cool color-picker adaptation for Angular 2. The Demo was fully functional as it was, but when I  imported it as an npm package the ./color-picker.html couldn't be found. It would be a waste not fixing this project. That's why is this pull request here.

We increased the version to 2.0.0, renamed the Demo to "example" and it uses the angular2-color-picker as an npm package. With this restructure of files, it is guaranteed, when example works, the color-picker will be working as an external npm package. We followed these instructions: https://medium.com/@OCombe/how-to-publish-a-library-for-angular-2-on-npm-5f48cdabf435#.ygkp0wsbe
and
http://blog.angular-university.io/how-to-create-an-angular-2-library-and-how-to-consume-it-jspm-vs-webpack/

To create "distribution version" we inline html and scss; we created a simple gulpfile.js to use for it.

Version 2.0.0 is not yet published to npm, we only tested with npm link and npm pack.

If you are agreed with our changes, then after this pull request, can you publish the version 2.0.0 ? We would use it immediately in our project.

Thank you!

### CODE REVIEW

**Comment by danielcrisp** [comment]
Yes! I'd like this too please :-)

**Comment by danielcrisp** [comment]
The `lib` directory is missing when I install from your pull request, like this:

    npm install github:Alberplz/angular2-color-picker#pull/11/head --save

**Comment by danielcrisp** [comment]
I have the same problem if I install directly from your fork too:

    npm install Csini/angular2-color-picker#feature\#makeNpmPackage --save

Confused!

**Comment by danielcrisp** [comment]
I think you're missing a `prepublish` script in the package.json to enable npm to transpile your TypeScript.

Also the `files` array in the package.json is preventing the src and gulpfile from being installed (but I don't know if that matters once it's up on npm)

**Comment by chron0** [comment]
Oh, +1, I'd like to try to use it in an ionic2 project and it would be awesome if it were available via npm to make maintenance/collaboration more easy with a simple entry in package.json where all the rest is maintained.

**Comment by Csini** [comment]
did you run the gulp script when you downloaded my branch in my fork? Built code like in this case in lib directory will I never commit into my git repository.

Npm package is an other thing: gulpfile.js is not included, because, we planned only to publish the content of the lib directory as a package. I think a good library is not needed to build anymore, if you are just using it, not changing it: everything should be built (with distribution parameters) before uploading as an npm package. am I wrong?

**Comment by Csini** [comment]
until the package is published in npm I do:

1. git clone https://github.com/Csini/angular2-color-picker.git
2. npm install
3. npm start (it creates lib directory with gulp)
4. npm pack (it creates angular2-color-picker-2.0.0.tgz)
5. go to your project
6. npm install [your_path]/angular2-color-picker-2.0.0.tgz

typings and gulp should be available as global runnable npm packages

**Comment by chron0** [comment]
Sorry, I've never bundled an NPM package so I really have no idea how that would look from a maintainer's point of view. I'll try to use your last comment to bring it to live, typings and gulp should be covered globally on my dev boxes, since I require them for my project as well. Thanks for the feedback, I'm looking forward to try it out.

**Comment by danielcrisp** [comment]
I tried installing with npm, as above, however there is an issue with npm which means that it doesn't run the `prepublish` command when you install from github... see https://github.com/npm/npm/issues/3055

As a workaround I tried using this https://github.com/lzrski/npm-git-install but that also didn't work for me.

I agree that you shouldn't include compiled code in the repo, but the built version should be available when you install via npm, so (I think) you need to define the build commands in the `prepublish` option so that npm can run the build process when you publish to the registry. So _I think_ that should be included in your PR. That said, I've no experience of this myself so I could be wrong!

The process you describe above seems like a good way to handle the build until the PR is merged and published though.

**Comment by Csini** [comment]
I have
npm -v
3.10.2
node -v
v6.2.2
@danielcrisp you?

**Comment by danielcrisp** [comment]
I use [n](https://github.com/tj/n) so I have various... but currently I'm running:

```
npm -v
3.6.0
node -v
v.5.6.0
```

**Comment by Raymice** [comment]
It's works with this command : 
git clone -b feature#makeNpmPackage https://github.com/Csini/angular2-color-picker.git

And then : 
2. npm install
3. npm start (it creates lib directory with gulp)
4. npm pack (it creates angular2-color-picker-2.0.0.tgz)
5. go to your project
6. npm install [your_path]/angular2-color-picker-2.0.0.tgz

**Comment by Gillardo** [comment]
Would love to use this colorpicker, but can you please enable npm...

**Comment by Csini** [comment]
https://github.com/Alberplz/angular2-color-picker/issues/12

**Comment by Csini** [comment]
@Alberplz Something went wrong with the merge! I don't see any changes in your mater and the packag, which is uploaded to npm.js is also wrong, I get

ERROR in ./~/angular2-color-picker/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/index.js in /home/csini/work/dailymenuboard/node_modules/angular2-color-picker
 @ ./~/angular2-color-picker/index.js 10:9-34

only the content of the lib folder should be in the npm package --y you ca set it with "outDir": "lib" in the tsconfig.json

**Pull request merged**
