### PR TITLE
Fix for compilation with AoT and AngularCLI

### PR DESCRIPTION
**Pull request by Zerogiven**
Just a small fix for those errors:
ERROR in Cannot determine the module for class TextDirective in .../node_modules/angular2-color-picker/lib/color-picker.directive.ts!
Cannot determine the module for class SliderDirective in .../node_modules/angular2-color-picker/lib/color-picker.directive.ts!
Cannot determine the module for class DialogComponent in .../node_modules/angular2-color-picker/lib/color-picker.directive.ts!

### CODE REVIEW

**Comment by Zerogiven** [comment]
Ups sorry, did not saw that it's already in progress with another pull request...

**Comment by Zerogiven** [comment]
But this patch would be needed for me and my team to make a succesfull build, so at the moment i copied your code into my src/ and import this with my fix till an update ;) cheers

**Comment by chrishawn** [comment]
thanks just ran into this as well... would be nice for it to drop into master soon

**Comment by born2net** [comment]
Hi,
any chance we can get it working with ng-cli / AOT?
Thanks for a  great lib, just needing AOT support,
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by Zerogiven** [comment]
@born2net you can look at the "files changed" tab and make the changes by yourself at the moment. To have it in your repo i suggest you temporarily copy the angular color picker module inside your project (src/app, for example). After this you just have to import it from your directory location not from node_modules.

```typescript
import { ColorPickerModule } from './your-folder-where-you-saved-the-color-picker.../';
```

cheers

**Comment by born2net** [comment]
tx I have used the other repo for now that added AOT.
Tx for replying.
https://github.com/zefoy/ngx-color-picker

**Comment by ghost** [comment]
Any news on this PR? When will be merged?

**Pull request closed without merging**
