### PR TITLE
Support to 8 digits HEX with alpha

### PR DESCRIPTION
**Pull request by mlessio**
Enables output like #AABBCCFF if hex output is selected instead of rgba() notation

### CODE REVIEW

**Comment by Alberplz** [comment]
Browsers don't support 8 digits HEX

**Comment by mlessio** [comment]
That's true, browsers don't(or better, they don't right now).
But it is not told you are going to use it in a browser.

I think if i choose to output in HEX, i want an HEX output, not an rgba one.

Cheers!

**Comment by Alberplz** [comment]
Yes I know. If is only the ouput you can use:
<input [colorPicker]="color" (colorPickerChange)="hex8=onChangeColor($event)"/>

But if hex8 support is added I think the input should too (users also can manipulate the color from de input)

**Comment by Alberplz** [comment]
'<input [colorPicker]="color" (colorPickerChange)="hex8=onChangeColor($event)"/>'

**Comment by Alberplz** [comment]
`<input [colorPicker]="color" (colorPickerChange)="hex8=onChangeColor($event)"/>`

**Comment by Alberplz** [comment]
Yes I know. If is only the ouput you can use:
`<input [colorPicker]="color" (colorPickerChange)="hex8=onChangeColor($event)"/>`

But if hex8 support is added I think the input should too (users also can manipulate the color from de input)

**Pull request closed without merging**
